# Generated by Django 5.1.3 on 2025-01-21 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_cars_owner_comment'),
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
