# Generated by Django 5.1.3 on 2025-01-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_cars_owner_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='isPurchased',
            field=models.BooleanField(default=False),
        ),
    ]
