# Generated by Django 5.1.3 on 2025-01-31 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_remove_cars_ispurchased_cars_purchased_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='purchased_by',
            new_name='purchasedBy',
        ),
    ]
