# Generated by Django 5.1.3 on 2025-01-31 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_rename_purchased_by_cars_purchasedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='owner',
        ),
    ]
